### ISSUE TITLE
Information and more details are needed about this dataset

### ISSUE THREAD

**Issue by Dragon615** [gabbygab1233/Crop-Recommendation#1]
Hi,,,

Nice work! 
Thanks for sharing!
 Has this dataset been used/introduced in any published paper? 
In other, I'm interested in using the dataset in my project, but I'm looking for more details about the process of data collection. Also, how should I cite your work? 

Thanks in advance for your response.

**Comment by gabbygab1233** [comment]
You can check more about the dataset [here](https://www.kaggle.com/atharvaingle/crop-recommendation-dataset). Use this to format to cite my work.

Miguel, Gabriel Jushua. "Crop Recommendation Using Machine Learning" (2020)

**Comment by Dragon615** [comment]
Great!
Thanks, gabbygab1233!
